/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RequestDemoRouteImport } from './routes/request-demo'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ProductsFindRouteImport } from './routes/products.find'
import { Route as ProductsRfqRouteImport } from './routes/products.rfq'
import { Route as ProductsRiskRouteImport } from './routes/products.risk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFindRoute = ProductsFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsRfqRoute = ProductsRfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsRiskRoute = ProductsRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/request-demo': typeof RequestDemoRoute
  '/resources': typeof ResourcesRoute
  '/sign-in': typeof SignInRoute
  '/solutions': typeof SolutionsRoute
  '/products/find': typeof ProductsFindRoute
  '/products/rfq': typeof ProductsRfqRoute
  '/products/risk': typeof ProductsRiskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/request-demo': typeof RequestDemoRoute
  '/resources': typeof ResourcesRoute
  '/sign-in': typeof SignInRoute
  '/solutions': typeof SolutionsRoute
  '/products/find': typeof ProductsFindRoute
  '/products/rfq': typeof ProductsRfqRoute
  '/products/risk': typeof ProductsRiskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/request-demo': typeof RequestDemoRoute
  '/resources': typeof ResourcesRoute
  '/sign-in': typeof SignInRoute
  '/solutions': typeof SolutionsRoute
  '/products/find': typeof ProductsFindRoute
  '/products/rfq': typeof ProductsRfqRoute
  '/products/risk': typeof ProductsRiskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/pricing'
    | '/products'
    | '/request-demo'
    | '/resources'
    | '/sign-in'
    | '/solutions'
    | '/products/find'
    | '/products/rfq'
    | '/products/risk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/pricing'
    | '/products'
    | '/request-demo'
    | '/resources'
    | '/sign-in'
    | '/solutions'
    | '/products/find'
    | '/products/rfq'
    | '/products/risk'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/pricing'
    | '/products'
    | '/request-demo'
    | '/resources'
    | '/sign-in'
    | '/solutions'
    | '/products/find'
    | '/products/rfq'
    | '/products/risk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  RequestDemoRoute: typeof RequestDemoRoute
  ResourcesRoute: typeof ResourcesRoute
  SignInRoute: typeof SignInRoute
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-demo': {
      id: '/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof RequestDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/find': {
      id: '/products/find'
      path: '/find'
      fullPath: '/products/find'
      preLoaderRoute: typeof ProductsFindRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/rfq': {
      id: '/products/rfq'
      path: '/rfq'
      fullPath: '/products/rfq'
      preLoaderRoute: typeof ProductsRfqRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/risk': {
      id: '/products/risk'
      path: '/risk'
      fullPath: '/products/risk'
      preLoaderRoute: typeof ProductsRiskRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsFindRoute: typeof ProductsFindRoute
  ProductsRfqRoute: typeof ProductsRfqRoute
  ProductsRiskRoute: typeof ProductsRiskRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsFindRoute: ProductsFindRoute,
  ProductsRfqRoute: ProductsRfqRoute,
  ProductsRiskRoute: ProductsRiskRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRouteWithChildren,
  RequestDemoRoute: RequestDemoRoute,
  ResourcesRoute: ResourcesRoute,
  SignInRoute: SignInRoute,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
